### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Yeafun** [Tree12323/Soochow_AutoLogin#1]
I cannot run it with chrome,can you fix it?

**Comment by Yeafun** [comment]
(base) yeafun@yeafun:~/文档/Soochow_AutoLogin-master$ nohup python Login.py 
nohup: 忽略输入并把输出追加到'nohup.out'

**Comment by Tree12323** [comment]
> I cannot run it with chrome,can you fix it?

问题解决,查看最新项目和README文件,可切换Chrome和Firefox浏览器.
